---
- name: Deploy for Ubuntu
  hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  roles:
    - { role: common, tags: common }
    - { role: ansible, tags: ansible }
    - { role: git, tags: git }
    - { role: subversion, tags: subversion }
    - { role: ufw, tags: ufw }
    - { role: vim, tags: vim }
    - { role: postgres, tags: postgres }
    - { role: apache2, tags: apache2 }
    - { role: php, tags: php }
    - { role: albert, tags: albert }
    - { role: acros, tags: acros }
