---
- name: Deploy for Ubuntu
  hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  roles:
#    - { role: common, tags: common }
#    - { role: git, tags: git }
#    - { role: subversion, tags: subversion }
    - { role: vim, tags: vim }
#    - { role: postgres, tags: postgres }
#    - { role: php, tags: php }
