---
- name: install / git clone or pull
  git:
    repo: https://github.com/phpredis/phpredis.git
    dest: /home/{{ ansible_env.SUDO_USER }}/tmp/phpredis
    version: php7
    update: yes
    accept_hostkey: true
    depth: 1

- name: configure / phpize
  command: phpize
  args:
    chdir: /home/{{ ansible_env.SUDO_USER }}/tmp/phpredis

- name: configure / configure
  command: ./configure
  args:
    chdir: /home/{{ ansible_env.SUDO_USER }}/tmp/phpredis

- name: configure / make all
  make:
    chdir: /home/{{ ansible_env.SUDO_USER }}/tmp/phpredis
    target: all

- name: configure / make install
  make:
    chdir: /home/{{ ansible_env.SUDO_USER }}/tmp/phpredis
    target: install

- name: configure / copy
  copy:
    src: redis.ini
    dest: /etc/php/7.1/mods-available/redis.ini
    force: yes

- name: configure / link
  file:
    src: /etc/php/7.1/mods-available/redis.ini
    dest: /etc/php/7.1/apache2/conf.d/redis.ini
    state: link

- name: configure / link
  file:
    src: /etc/php/7.1/mods-available/redis.ini
    dest: /etc/php/7.1/cli/conf.d/redis.ini
    state: link

- name: restart apache2 service
  systemd:
    name: apache2
    state: restarted
