---
## 1.IPv6インターフェイス無効化
#- name: configure / Desable ipv6 interface
#  sysctl:
#    state: present
#    name: "{{ item }}"
#    value: 1
#    sysctl_set: yes
#    reload: yes
#  with_items:
#    - net.ipv6.conf.all.disable_ipv6
#    - net.ipv6.conf.default.disable_ipv6

## 2.aptパッケージのアップデート
#- name: configure / Upgrade apt packages
#  apt:
#    upgrade: dist
#    update_cache: yes

## 3.自動アップデート
#- name: configure / Upgrade apt packages
#  apt:
#    name: unattended-upgrades


