---
## 1.IPv6インターフェイス無効化
#- name: configure / Desable ipv6 interface
#  sysctl:
#    state: present
#    name: "{{ item }}"
#    value: 1
#    sysctl_set: yes
#    reload: yes
#  with_items:
#    - net.ipv6.conf.all.disable_ipv6
#    - net.ipv6.conf.default.disable_ipv6

## 2.aptパッケージのアップデート
#- name: configure / Upgrade apt packages
#  apt:
#    upgrade: dist
#    update_cache: yes

## 3.自動アップデート
#- name: configure / Upgrade apt packages
#  apt:
#    name: unattended-upgrades


## alias
- block:
  - name: configure / Add Alias ll
    lineinfile:
      dest: ~/.bashrc
      line: "alias ll='ls -la --color=auto'"

  - name: configure / Add Alias df
    lineinfile:
      dest: ~/.bashrc
      line: "alias df='df -h'"

  - name: configure / source
    shell: source ~/.bashrc executable=/bin/bash

## ホームディレクトリ名をローマ字に
- name: configure / Set Home Dirctory Name
  shell: LANG=C xdg-user-dirs-gtk-update
