---
## 1.php設定の配備
- name: configure / Setup global configuration file
  template:
    src: php.ini.j2
    dest: /etc/php/7.1/apache2/php.ini
    owner: root
    group: root
    mode: 0644
  notify: restart httpd service

## 2.apache用設定ファイルの配備
- name: configure / Setup apache configuration file
  copy:
    src: php.conf
    dest: /etc/httpd/conf.d/php.conf
  notify: restart httpd service
